name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install project dependencies
        run: |
          pip install tensorflow==2.0.0
          pip install -e .[test]
      - name: Run Flake8
        run: flake8
      - name: Black code style
        run: black --check --target-version py36 --exclude 'build/|\.mypy_cache/|\.venv/|env/|larq/snapshots/|.pytype/' .
